Sys.setlocale('LC_CTYPE','English_United States.utf8');root<-getwd();dir.create('test-output',showWarnings=FALSE);source('app.R',encoding='UTF-8')
stopifnot(identical(formals(parallel_analysis)$B,500),!any(grepl('混雜因子',readLines('app.R',encoding='UTF-8'))))
shiny::testServer(server,{
 session$setInputs(demo=1,design='cohort',structure='independent',purpose='measurement',module='reliability',rel_entry='text',items=paste0('Q',1:3),reverse=character(),bootstrap_ci=FALSE,seed=1,B=20,run=1)
 stopifnot('Reliability'%in%names(result()$tables),!'Parallel'%in%names(result()$tables))
 session$setInputs(module='efa',cor_method='spearman',permutations=20,nfactor=1,run=2)
 stopifnot('Loadings'%in%names(result()$tables),!'Reliability'%in%names(result()$tables))
 session$setInputs(module='cfa',cfa_entry='syntax',cfa_syntax='F1 =~ Q1+Q2+Q3\nF2 =~ Q4+Q5+Q6',ordered=paste0('Q',1:6),estimator='WLSMV',validation='same',run=3)
 stopifnot(result()$title=='驗證性因素分析 CFA')
 session$setInputs(syntax='F1 =~ Q1+Q2+Q3\nF2 =~ Q4+Q5+Q6\nF2 ~ F1',run=4)
 stopifnot(result()$title=='分析未完成')
 session$setInputs(purpose='path',module='sem',run=5)
 stopifnot('Parameters'%in%names(result()$tables))
})
f<-tempfile(fileext='.csv');writeBin(as.raw(c(charToRaw('X,Name\n1,'),0xa4,0xa4,10)),f)
stopifnot(inherits(try(read_dataset(f),silent=TRUE),'try-error'))
z<-read_dataset(f,encoding='CP950');stopifnot(nrow(z)==1,z$Name=='中');unlink(f)
stopifnot(identical(regression_models('casecontrol','binary'),c('Binary Logistic → OR'='logistic')))
cat('PASS 500 default, split reliability EFA CFA SEM, CFA structure guard, UTF8 rejection and CP950 decode\n')
# Record bundled versions used by this release.
ip<-installed.packages(lib.loc='library');write.csv(ip[,c('Package','Version'),drop=FALSE],'package-versions.csv',row.names=FALSE)
