Sys.setlocale('LC_CTYPE','English_United States.utf8');.libPaths(c('library',.libPaths()));library(shiny)
source('R/core.R',encoding='UTF-8');source('R/sem_types.R',encoding='UTF-8');source('R/model_builder.R',encoding='UTF-8')
server_test<-function(input,output,session){
 raw<-reactiveVal(data.frame(q1=1:20,q2=2:21,q3=3:22,q4=4:23,q5=5:24,q6=6:25,y=seq_len(20)))
 choices<-reactive(names(raw()));builder<-setup_model_builder(input,output,session,raw,choices,raw)
}
testServer(server_test,{
 session$setInputs(module='sem');session$flushReact()
 session$setInputs(sem_node_1_code='F1',sem_node_1_label='工作環境',sem_node_1_kind='latent',sem_node_1_items=c('q1','q2','q3'))
 session$setInputs(sem_y_label='衛生所轉型',sem_y_kind='observed',sem_y_variable='y',sem_y_type='continuous')
 session$setInputs(builder_action=list(action='add_edge',id=''))
 session$setInputs(sem_edge_1_from='1',sem_edge_1_to='outcome',sem_edge_1_type='regression')
 s<-builder$sem();stopifnot(grepl('F1 =~ q1 + q2 + q3',s$syntax,fixed=TRUE),grepl('y ~ F1',s$syntax,fixed=TRUE))
 session$setInputs(builder_action=list(action='add_node',id=''));session$setInputs(builder_action=list(action='remove_node',id='2'))
 stopifnot(identical(builder$sem()$syntax,s$syntax));cat('PASS: add/remove unrelated node preserves entered model\n')
 session$setInputs(sem_node_1_items=NULL);e<-tryCatch(builder$sem(),error=conditionMessage);stopifnot(is.character(e),grepl('至少 3',e));cat('PASS: clearing selection does not restore previous items\n')
 session$setInputs(sem_node_1_items=c('q1','q2','q3'));session$setInputs(builder_action=list(action='remove_node',id='1'))
 session$setInputs(builder_action=list(action='add_node',id=''));session$setInputs(sem_node_3_code='F1',sem_node_3_kind='latent',sem_node_3_items=c('q1','q2','q3'))
 e<-tryCatch(builder$sem(),error=conditionMessage);stopifnot(grepl('通往',e));cat('PASS: removing node removes incident paths\n')
 session$setInputs(module='efa',efa_group_1_label='第一構面',efa_group_1_items=c('q1','q2','q3'))
 session$setInputs(builder_action=list(action='add_group',id=''));session$setInputs(efa_group_2_label='第二構面',efa_group_2_items=c('q4','q5','q6'))
 stopifnot(length(builder$efa()$items)==6)
 session$setInputs(builder_action=list(action='remove_group',id='2'));stopifnot(identical(builder$efa()$items,c('q1','q2','q3')));cat('PASS: EFA groups preserve selections through add/remove\n')
 session$setInputs(efa_group_1_items=NULL);e<-tryCatch(builder$efa(),error=conditionMessage);stopifnot(grepl('至少 3',e));cat('PASS: EFA clear is validated before analysis\n')
})
