Sys.setlocale('LC_CTYPE','English_United States.utf8');source('app.R',encoding='UTF-8')
dir.create('test-output',showWarnings=FALSE)
checks<-character();ok<-function(x,label){stopifnot(isTRUE(x));checks<<-c(checks,label);cat('PASS:',label,'\n')}
fails<-function(expr,text){e<-tryCatch({force(expr);''},error=conditionMessage);grepl(text,e,fixed=TRUE)}
set.seed(914);n<-900;latent_a<-rnorm(n);latent_b<-.5*latent_a+rnorm(n)
d<-data.frame(Q1=latent_a+rnorm(n,.0,.6),Q2=latent_a+rnorm(n,.0,.6),Q3=latent_a+rnorm(n,.0,.6),Q4=latent_b+rnorm(n,.0,.6),Q5=latent_b+rnorm(n,.0,.6),Q6=latent_b+rnorm(n,.0,.6))
for(v in names(d))d[[v]]<-ordered(cut(d[[v]],c(-Inf,-1,0,1,Inf),labels=FALSE))
d$Event<-factor(as.integer(.4*latent_a+.6*latent_b+rnorm(n)>0));d$Continuous<-.3*latent_b+rnorm(n)
d$Grade<-ordered(cut(.5*latent_b+rnorm(n),c(-Inf,-.6,.6,Inf),labels=c('低','中','高')));d$Nominal<-factor(rep(c('A','B','C'),length.out=n));d$Y<-rnorm(n)
ok(fails(sem_outcome_spec(d,variable='Event'),'選擇事件組'),'binary endpoint requires an explicit event selection')
y<-sem_outcome_spec(d,variable='Event',event='1');z<-sem_outcome_data(d,y)
ok(y$type=='binary'&&identical(levels(z$Event),c('0','1'))&&is.factor(d$Event)&&!is.ordered(d$Event),'binary coding uses selected event and leaves imported data unchanged')
ok(fails(sem_outcome_spec(d,variable='Nominal'),'多類別名目'),'nominal multi-category endpoint is rejected clearly')
ok(fails(sem_outcome_spec(d,variable='Event',type='continuous'),'連續 Y'),'nominal numeric codes are not silently treated as continuous')
ok(identical(sem_outcome_spec(d,variable='Grade')$levels,c('低','中','高')),'ordinal endpoint preserves confirmed level order')
ok(fails(sem_outcome_spec(d,variable='Grade',type='ordinal',level_text='高 | 低'),'完整且不重複'),'incomplete ordinal endpoint levels are blocked')
ok(sem_outcome_spec(d,kind='latent',items=c('Q4','Q5','Q6'))$symbol!='Y','latent endpoint avoids observed Y name collision')
shiny::testServer(server,{
 ingest(d,'Synthetic endpoint validation');session$flushReact()
 session$setInputs(design='cross',structure='independent',purpose='path',module='sem',sem_entry='builder',estimator='WLSMV',B=20,bootstrap_ci=FALSE,seed=914,validation='same')
 session$setInputs(sem_y_kind='observed',sem_y_variable='Event',sem_y_type='auto',sem_y_event='',sem_node_1_code='F1',sem_node_1_kind='latent',sem_node_1_items=c('Q1','Q2','Q3'),builder_action=list(action='add_node',id=''))
 session$setInputs(sem_node_2_code='F2',sem_node_2_kind='latent',sem_node_2_items=c('Q4','Q5','Q6'),builder_action=list(action='add_edge',id=''))
 session$setInputs(sem_edge_1_from='1',sem_edge_1_to='2',sem_edge_1_type='regression',builder_action=list(action='add_edge',id=''))
 session$setInputs(sem_edge_2_from='1',sem_edge_2_to='outcome',sem_edge_2_type='regression',builder_action=list(action='add_edge',id=''))
 session$setInputs(sem_edge_3_from='2',sem_edge_3_to='outcome',sem_edge_3_type='regression',run=1)
 ok(result()$title=='分析未完成'&&any(grepl('選擇事件組',result()$notes)),'omitted event is caught in dedicated Y area before fitting')
 session$setInputs(sem_y_event='1',ordered=c('Nominal','Y','Absent','Event','Q1','Q2'),run=2)
 r<-result();ok(r$title!='分析未完成'&&r$sem_outcome$event=='1'&&r$sem_outcome$reference=='0'&&'Event'%in%r$settings$ordered,'guided binary endpoint fits without manual ordered selection')
 ok(!any(c('Nominal','Y','Absent')%in%r$settings$ordered)&&length(r$settings$ordered_requested)==0,'stale extra selections cannot block analysis or enter the model')
 ok('SEM_outcome'%in%names(r$tables)&&r$tables$SEM_variable_types$Source[r$tables$SEM_variable_types$Variable=='Event']=='Y 獨立設定','result records endpoint coding and its source')
 ref<-lavaan::sem(r$settings$syntax,sem_outcome_data(data(),r$sem_outcome),ordered=r$settings$ordered,estimator='WLSMV',missing='listwise')
 ok(isTRUE(all.equal(r$tables$Parameters$est,lavaan::parameterEstimates(ref)$est,tolerance=1e-10)),'dedicated endpoint estimates match direct lavaan fit')
 old<-r$tables$Parameters;session$setInputs(sem_y_event='0',run=3);now<-result()$tables$Parameters
 ii<-which(old$lhs=='Event'&old$op=='~');ok(all(abs(now$est[ii]+old$est[ii])<1e-6)&&result()$sem_outcome$reference=='1','reversing selected binary event reverses outcome coefficients')
 session$setInputs(builder_action=list(action='add_node',id=''));session$setInputs(builder_action=list(action='remove_node',id='3'))
 ok(builder$outcome()$event=='0'&&builder$outcome()$variable=='Event','adding or removing other constructs preserves endpoint configuration')
 session$setInputs(sem_edge_3_from='outcome');ok(fails(builder$sem(),'Y 是終點結果'),'outgoing endpoint path is rejected')
 session$setInputs(sem_edge_3_from='2',sem_y_variable='Grade',sem_y_type='ordinal',sem_y_levels='低 | 中 | 高',run=4)
 ok(result()$title!='分析未完成'&&identical(result()$sem_outcome$levels,c('低','中','高')),'ordinal endpoint runs with its dedicated level order')
 session$setInputs(sem_y_variable='Continuous',sem_y_type='continuous',run=5)
 ok(result()$title!='分析未完成'&&!('Continuous'%in%result()$settings$ordered),'continuous endpoint remains numeric with ordinal predictors')
 session$setInputs(sem_y_kind='latent',sem_y_items=c('Q4','Q5','Q6'),builder_action=list(action='remove_node',id='2'))
 session$setInputs(run=6);ok(result()$title!='分析未完成'&&result()$sem_outcome$type=='latent'&&grepl('Y_latent =~',result()$settings$syntax),'latent endpoint fits using its own measurement items')
 session$setInputs(sem_y_items=character(),run=7);ok(result()$title=='分析未完成'&&any(grepl('至少 3',result()$notes)),'cleared endpoint items do not silently restore')
 saveRDS(r,'test-output/SEM_endpoint_result.rds')
})
writeLines(checks,'test-output/sem_endpoint_checks.txt',useBytes=TRUE)
