Sys.setlocale('LC_CTYPE','English_United States.utf8');source('app.R',encoding='UTF-8')
dir.create('test-output',showWarnings=FALSE)
checks<-character();ok<-function(x,label){stopifnot(isTRUE(x));checks<<-c(checks,label);cat('PASS:',label,'\n')}
fails<-function(expr,pattern){e<-tryCatch({force(expr);''},error=conditionMessage);grepl(pattern,e,fixed=TRUE)}
g<-function(id,items,label=paste0('構面 ',id))list(id=as.character(id),code=paste0('F',id),label=label,items=items)
vars<-paste0('Q',1:6);groups<-list(g(1,vars[1:3],'工作環境'),g(2,vars[4:6],'疲勞'))
s<-measurement_group_spec(groups,vars,'cfa');pt<-lavaan::lavaanify(s$syntax)
ok(sum(pt$op=='=~')==6&&!any(pt$op=='~')&&all(c('F1','F2')%in%names(s$labels)),'CFA cards create measurement definitions without an endpoint or structural regression')
ok(fails(measurement_group_spec(list(g(1,vars[1:2])),vars,'cfa'),'至少 3'),'two-item CFA directs to explicit identification constraints')
ok(fails(measurement_group_spec(list(g(1,vars[1:3]),g(2,vars[3:6])),vars,'cfa'),'跨負荷'),'duplicate CFA assignments are caught with the conflicting item')
ok(fails(measurement_group_spec(groups,vars[-1],'cfa'),'不存在'),'excluded CFA variables cannot enter the fitted model')
overlap<-measurement_group_spec(list(g(1,vars[1:2],'分量表'),g(2,vars[1:3],'整體量表')),vars,'reliability')
ok(length(overlap$items)==3&&length(reliability_groups(overlap$items,overlap$groups))==2,'reliability permits shared items in distinct whole-scale and subscale cards')
# Reproducible synthetic ordinal and continuous observations, never user data.
set.seed(917);n<-450;eta1<-rnorm(n);eta2<-.4*eta1+rnorm(n);d<-data.frame(ID=seq_len(n),Age=runif(n,25,80))
for(i in 1:6)d[[vars[i]]]<-ordered(cut(list(eta1,eta2)[[ceiling(i/3)]]+rnorm(n,sd=.6),c(-Inf,-.8,-.2,.3,.9,Inf),labels=FALSE))
shiny::testServer(server,{
 ingest(d,'Synthetic CFA and reliability cards');session$flushReact()
 session$setInputs(design='cross',structure='independent',purpose='measurement',module='cfa',cfa_entry='builder',estimator='auto',validation='same',bootstrap_ci=FALSE,B=20,seed=917,
  cfa_group_1_code='F1',cfa_group_1_label='工作環境',cfa_group_1_items=vars[1:3],builder_action=list(action='add_cfa',id=''))
 session$setInputs(cfa_group_2_code='F2',cfa_group_2_label='疲勞',cfa_group_2_items=vars[4:6],cfa_correlation='correlated',ordered=c('Age','Absent'),run=1)
 r<-result();ok(r$title=='驗證性因素分析 CFA'&&r$settings$estimator=='WLSMV'&&r$settings$estimator_requested=='auto','CFA card flow automatically resolves ordinal items to WLSMV')
 ok(setequal(r$settings$ordered,vars)&&!length(r$settings$ordered_requested),'CFA ordered settings ignore unrelated stale selections')
 ref<-lavaan::cfa(s$syntax,d,ordered=vars,estimator='WLSMV',missing='listwise')
 ok(max(abs(r$tables$Parameters$est-lavaan::parameterEstimates(ref)$est))<1e-8,'guided CFA estimates match direct lavaan CFA with selected factors and correlations')
 ok(identical(r$tables$CFA_constructs$Label,c('工作環境','疲勞'))&&r$plots$SEM_diagram$labels$title=='Confirmatory factor analysis','construct names are retained in results and the plot is labeled CFA')
 session$setInputs(builder_action=list(action='add_cfa',id=''));session$setInputs(builder_action=list(action='remove_cfa',id='3'))
 ok(identical(builder$cfa()$syntax,s$syntax),'adding and removing another CFA construct preserves existing selections and labels')
 session$setInputs(cfa_group_2_items=character());ok(fails(builder$cfa(),'至少 3'),'clearing a CFA card does not restore old selections')
 session$setInputs(cfa_group_2_items=vars[4:6],cfa_correlation='orthogonal',run=2)
 rr<-result();pp<-rr$tables$Parameters
 ok(rr$title!='分析未完成'&&all(pp$est[pp$op=='~~'&pp$lhs=='F1'&pp$rhs=='F2']==0),'orthogonal CFA fixes between-factor covariance to zero')
 session$setInputs(estimator='MLR',run=3);ok(result()$title=='分析未完成'&&any(grepl('WLSMV',result()$notes)),'manual incompatible estimator remains blocked')
 session$setInputs(cfa_entry='syntax',cfa_syntax=s$syntax,estimator='auto',run=4)
 ok(result()$title!='分析未完成'&&identical(result()$settings$syntax,s$syntax),'advanced CFA syntax remains separate from the card model')
 session$setInputs(module='reliability',rel_entry='builder',rel_group_1_label='兩題分量表',rel_group_1_items=vars[1:2],rel_seed=917,rel_subject_id='ID',rel_labels='',rel_reverse=character(),builder_action=list(action='add_rel',id=''))
 session$setInputs(rel_group_2_label='三題量表',rel_group_2_items=vars[1:3],run=5)
 rel<-result();ok(rel$title!='分析未完成'&&identical(rel$tables$Reliability$Items,c(2L,3L))&&all(rel$tables$Bootstrap$Requested==5000),'reliability cards retain two/three-item methods and the full 5000 bootstraps')
 it<-rel$tables$Items;ok(all(is.na(it$CITC[it$Scale=='兩題分量表']))&&all(is.finite(it$CITC[it$Scale=='三題量表']))&&is.finite(rel$tables$Reliability$Spearman_Brown[1]),'two-item cards use Spearman-Brown while three-item cards retain CITC')
 expected<-reliability_coefficients(sapply(d[vars[1:3]],num))['Raw_alpha']
 ok(abs(rel$tables$Reliability$Alpha[2]-expected)<1e-10&&identical(rel$settings$items,vars[1:3]),'card selections use original scored-item coefficients and freeze the exact union of selected items')
 session$setInputs(builder_action=list(action='add_rel',id=''));session$setInputs(builder_action=list(action='remove_rel',id='3'))
 ok(identical(builder$reliability()$groups,'兩題分量表 = Q1, Q2\n三題量表 = Q1, Q2, Q3'),'reliability selections and group names survive adding/removing cards')
 session$setInputs(rel_reverse='Q2',rel_lower=NA,rel_upper=NA,run=6)
 ok(result()$title=='分析未完成'&&any(grepl('理論最低',result()$notes)),'selected reverse items require theoretical scale limits')
 session$setInputs(rel_lower=1,rel_upper=5,run=7);rev<-result();z<-sapply(d[vars[1:3]],num);z[,'Q2']<-6-z[,'Q2']
 ok(rev$title!='分析未完成'&&abs(rev$tables$Reliability$Alpha[2]-reliability_coefficients(z)['Raw_alpha'])<1e-10,'reverse scoring from the new controls reaches the reliability calculation')
 session$setInputs(module='cfa',cfa_entry='builder',cfa_correlation='correlated')
 ok(identical(builder$cfa()$syntax,s$syntax)&&identical(builder$reliability()$items,vars[1:3]),'CFA and reliability retain independent card selections when switching modes')
 session$setInputs(module='reliability',rel_entry='text',items=vars[4:6],rel_groups='',rel_reverse=character(),run=8)
 ok(result()$title!='分析未完成'&&identical(result()$reliability_spec$groups[[1]],vars[4:6]),'legacy text reliability input remains available without using hidden cards')
 session$setInputs(rel_entry='builder',rel_group_2_items=character());ok(fails(builder$reliability(),'至少 2'),'cleared reliability selections are validated instead of restored')
 saveRDS(r,'test-output/CFA_cards_result.rds');saveRDS(rel,'test-output/Reliability_cards_result.rds')
})
continuous<-data.frame(q1=eta1+rnorm(n,sd=.5),q2=eta1+rnorm(n,sd=.6),q3=eta1+rnorm(n,sd=.6))
shiny::testServer(server,{
 ingest(continuous,'Synthetic continuous CFA');session$flushReact()
 session$setInputs(design='cross',structure='independent',purpose='measurement',module='cfa',cfa_entry='builder',cfa_group_1_code='F1',cfa_group_1_items=names(continuous),estimator='auto',bootstrap_ci=FALSE,B=20,seed=917,validation='same',run=1)
 ok(result()$title!='分析未完成'&&result()$settings$estimator=='MLR'&&any(grepl('剛好識別',result()$notes)),'single-factor continuous CFA resolves to MLR and reports zero-df limitation')
})
writeLines(checks,'test-output/measurement_cards_checks.txt',useBytes=TRUE)
