Sys.setlocale('LC_CTYPE','English_United States.utf8');source('app.R',encoding='UTF-8')
dir.create('test-output',showWarnings=FALSE)
checks<-character();ok<-function(x,label){stopifnot(isTRUE(x));checks<<-c(checks,label);cat('PASS:',label,'\n')}
fails<-function(expr,text){e<-tryCatch({force(expr);''},error=conditionMessage);grepl(text,e,fixed=TRUE)}
# All test observations are synthetic. Age deliberately excludes 0 and 1:
# a per-unit effect must not demand nonexistent reference ages 0 and 1.
set.seed(916);n<-500;d<-data.frame(Age=runif(n,35,80),C=rnorm(n))
d$Instrument<-.08*d$Age+.2*d$C+rnorm(n);d$Biomarker<-.03*d$Age+.5*d$Instrument+.15*d$C+rnorm(n)
d$Group<-factor(rep(c('A','B','C','A','B'),length.out=n))
ok(fails(ordinary_mediation(d,'Age','Instrument','Biomarker',a0=NULL,a1=NULL),'請填寫參考數值'),'blank explicit contrast reports the missing values and observed range')
unit<-ordinary_mediation(d,'Age','Instrument','Biomarker','C',exposure_scale='unit')
mi<-lm(Instrument~Age+C,d);yi<-lm(Biomarker~Age+Instrument+C,d)
expected<-c(coef(yi)['Age'],coef(mi)['Age']*coef(yi)['Instrument'],coef(yi)['Age']+coef(mi)['Age']*coef(yi)['Instrument'])
ok(max(abs(unit$tables$Mediation$Estimate-expected))<1e-7&&unit$tables$Sample$N==n,'continuous-X unit effects equal independent linear-model slopes without grouping')
ten<-ordinary_mediation(d,'Age','Instrument','Biomarker','C',exposure_scale='unit',exposure_change=10)
cols<-c('Estimate','CI_low','CI_high')
ok(max(abs(as.matrix(ten$tables$Mediation[cols])-10*as.matrix(unit$tables$Mediation[cols])))<1e-7&&identical(unit$tables$Mediation$p_value,ten$tables$Mediation$p_value),'ten-unit estimates and confidence limits scale together without changing p values')
values<-ordinary_mediation(d,'Age','Instrument','Biomarker','C',50,60)
ok(isTRUE(all.equal(values$tables$Mediation,ten$tables$Mediation))&&values$tables$Sample$N==n,'explicit 50-to-60 contrast equals ten-unit effects and retains all continuous-X observations')
rev<-ordinary_mediation(d,'Age','Instrument','Biomarker','C',60,50)
ok(max(abs(rev$tables$Mediation$Estimate+ten$tables$Mediation$Estimate))<1e-7&&all(rev$tables$Mediation$CI_low<=rev$tables$Mediation$CI_high),'reversing the contrast reverses signs while keeping confidence bounds ordered')
ok(fails(ordinary_mediation(d,'Age','Instrument','Biomarker',exposure_scale='unit',exposure_change=0),'大於 0')&&fails(ordinary_mediation(d,'Age','Instrument','Biomarker',exposure_scale='unit',exposure_change=NA),'大於 0'),'zero or missing unit changes are rejected')
ok(fails(ordinary_mediation(d,'Age','Instrument','Biomarker',a0=0,a1=1),'完整個案的觀察範圍'),'out-of-range explicit contrasts remain rejected')
group<-ordinary_mediation(d,'Group','Instrument','Biomarker',a0='A',a1='B',exposure_scale='unit')
ok(group$tables$Exposure_contrast$Scale=='groups'&&group$tables$Sample$Other_exposure_excluded==sum(d$Group=='C'),'categorical-X comparisons keep selected groups despite stale continuous-unit settings')
b1<-ordinary_mediation(d,'Age','Instrument','Biomarker','C',boot=TRUE,B=20,seed=17,exposure_scale='unit')
b10<-ordinary_mediation(d,'Age','Instrument','Biomarker','C',boot=TRUE,B=20,seed=17,exposure_scale='unit',exposure_change=10)
ok(max(abs(as.matrix(b10$tables$Mediation[cols])-10*as.matrix(b1$tables$Mediation[cols])))<1e-6,'same subject-bootstrap samples preserve requested exposure units in estimates and intervals')
causal<-causal_mediation(d,'Age','Instrument','Biomarker',a0=50,a1=60,mreg='linear',yreg='linear',m_cde=4,design='cohort',reviewed=TRUE)
ok(all(is.finite(causal$tables$Causal_effects$Estimate))&&causal$tables$Sample$N==n,'causal mediation still fits continuous X with an explicit contrast')
ok(fails(causal_mediation(d,'Age','Instrument','Biomarker',a0=NULL,a1=NULL,mreg='linear',yreg='linear',m_cde=4,design='cohort',reviewed=TRUE),'請填寫參考數值'),'causal mediation does not inherit the ordinary per-unit shortcut')
shiny::testServer(server,{
 ingest(d,'Synthetic continuous-X validation');session$flushReact()
 session$setInputs(design='cross',structure='independent',purpose='path',module='mediation',med_a='Age',med_m='Instrument',med_y='Biomarker',med_covars='C',bootstrap_ci=FALSE,seed=916)
 session$setInputs(med_a0=0,med_a1=1,run=1)
 r<-result();ok(r$title!='分析未完成'&&r$settings$med_exposure_scale=='unit'&&is.null(r$settings$med_a0)&&is.null(r$settings$med_a1),'UI defaults to a one-unit effect and excludes inactive old contrast values from the record')
 ok(grepl('連續 X 的效果單位',output$med_contrast$html,fixed=TRUE)&&grepl('觀察範圍',output$med_contrast$html,fixed=TRUE),'continuous-X controls display the effect-unit choice and observed range')
 session$setInputs(med_exposure_change=10,run=2)
 ok(isTRUE(all.equal(result()$tables$Mediation,ten$tables$Mediation))&&grepl('每增加 10',result()$publication$note,fixed=TRUE),'selected units reach model estimates and the downloadable publication note')
 session$setInputs(med_exposure_scale='values',med_a0=50,med_a1=60,run=3)
 ok(result()$settings$med_exposure_scale=='values'&&isTRUE(all.equal(result()$tables$Mediation,values$tables$Mediation)),'UI explicit contrast remains available and uses the selected values')
 session$setInputs(design='cohort',module='causal_mediation')
 ok(!grepl('med_exposure_scale',output$med_contrast$html,fixed=TRUE)&&grepl('必填',output$med_contrast$html,fixed=TRUE),'switching to causal mediation shows mandatory explicit contrast controls')
 saveRDS(r,'test-output/mediation_continuous_x_result.rds')
})
writeLines(checks,'test-output/mediation_continuous_x_checks.txt',useBytes=TRUE)
