Sys.setlocale('LC_CTYPE','English_United States.utf8');root<-getwd();dir.create('test-output',showWarnings=FALSE);source('app.R',encoding='UTF-8')
set.seed(114);d<-data.frame(X=rnorm(100),Y=rnorm(100),Z=rnorm(100),G=factor(rep(c('A','B'),50)))
a<-descriptive(d,c('X','Y','Z'),'G',continuous_test='welch',p_adjust='bonferroni');t<-a$tables$Group_tests
stopifnot(all.equal(t$p_Bonferroni,pmin(1,t$p_value*3)),a$tables$Multiplicity$Planned_tests==3,'Bonferroni adj. p-value'%in%names(a$publication$data))
b<-correlation(d,c('X','Y','Z'),'pearson','bonferroni');t<-b$tables$Pairs;stopifnot(all.equal(t$p_Bonferroni,p.adjust(t$p_value,'bonferroni')),b$tables$Multiplicity$Planned_tests==3)
b<-correlation(d,c('X','Y'),'pearson','bonferroni');stopifnot(b$tables$Pairs$p_Bonferroni==b$tables$Pairs$p_value)
z<-d;z$Z<-1;b<-descriptive(z,c('X','Z'),'G',continuous_test='welch',p_adjust='bonferroni');stopifnot(b$tables$Multiplicity$Planned_tests==2,b$tables$Group_tests$p_Bonferroni[1]==min(1,2*b$tables$Group_tests$p_value[1]),is.na(b$tables$Group_tests$p_Bonferroni[2]))
stopifnot(display_table(data.frame(p_Bonferroni=.00009))$p_Bonferroni=='<0.0001')
export_docx(result_piece(a,'publication'),'test-output/Bonferroni_Table1_合成範例.docx');export_xlsx(result_piece(a,'publication'),'test-output/Bonferroni_Table1_合成範例.xlsx')
shiny::testServer(server,{ingest(d,'Synthetic multiple comparisons');session$setInputs(design='cohort',structure='independent',purpose='describe',module='descriptive',vars=c('X','Y'),group='G',summary='mean',continuous_test='welch',categorical_test='none',p_adjust='bonferroni',run=1);stopifnot('p_Bonferroni'%in%names(result()$tables$Group_tests));session$setInputs(purpose='association',module='correlation',vars=c('X','Y','Z'),cor_method='pearson',cor_p_adjust='bonferroni',run=2);stopifnot('p_Bonferroni'%in%names(result()$tables$Pairs))})
cat('PASS Bonferroni arithmetic, m=1, failed planned test, display and both Shiny flows\n')
saveRDS(a,file.path(root,'test-output','bonferroni_result.rds'))
