Sys.setlocale('LC_CTYPE','English_United States.utf8');root<-getwd();dir.create('test-output',showWarnings=FALSE);source('app.R',encoding='UTF-8')
stopifnot(abs(smd_pair(c(0,1,2),c(1,2,3))$SMD-1)<1e-12)
stopifnot(abs(smd_pair(factor(c(0,0,0,1)),factor(c(0,1,1,1)))$SMD-(.5/sqrt(.1875)))<1e-12)
stopifnot(is.infinite(smd_pair(rep(0,3),rep(1,3))$SMD),smd_pair(rep(1,3),rep(1,3))$SMD==0)
a<-factor(c('A','A','B','B','C'));b<-factor(c('A','B','C','C','C'));r<-smd_pair(a,b)$SMD;r2<-smd_pair(factor(a,levels=c('C','B','A')),factor(b,levels=c('C','B','A')))$SMD;stopifnot(abs(r-r2)<1e-12)
# Explicit independent calculation using all three indicators and a generalized inverse.
p<-c(.4,.4,.2);q<-c(.2,.2,.6);V<-((diag(p)-tcrossprod(p))+(diag(q)-tcrossprod(q)))/2;ref<-sqrt(drop(t(p-q)%*%MASS::ginv(V)%*%(p-q)));stopifnot(abs(r-ref)<1e-12)
d<-data.frame(X=c(0,1,2,1,2,3,2,3,4),F=factor(rep(c('a','b','c'),3)),G=factor(rep(c('A','B','C'),each=3)))
ans<-descriptive(d,c('X','F'),'G',compute_smd=TRUE);stopifnot(nrow(ans$tables$SMD_pairs)==6,ans$publication$data$`Max |SMD|`[ans$publication$data$Characteristic=='X']=='2.000')
shiny::testServer(server,{ingest(d,'Synthetic SMD');zz<-data();zz$X<-num(zz$X);data(zz);session$setInputs(design='cohort',structure='independent',purpose='describe',module='descriptive',vars=c('X','F'),group='G',summary='mean',continuous_test='anova',categorical_test='none',p_adjust='bonferroni',show_smd=TRUE,run=1);stopifnot('SMD_pairs'%in%names(result()$tables),'Bonferroni adj. p-value'%in%names(result()$publication$data))})
export_docx(result_piece(ans,'publication'),'test-output/SMD_Table1_合成範例.docx');export_xlsx(result_piece(ans,'publication'),'test-output/SMD_Table1_合成範例.xlsx');saveRDS(ans,file.path(root,'test-output','smd_result.rds'));cat('PASS continuous binary multinomial SMD, degeneracy, group pairs and Shiny\n')
