Sys.setlocale('LC_CTYPE','English_United States.utf8');.libPaths(c('library',.libPaths()))
library(shiny);source('R/core.R',encoding='UTF-8');source('R/models.R',encoding='UTF-8');source('R/export.R',encoding='UTF-8');source('R/model_builder.R',encoding='UTF-8')
dir.create('test-output',showWarnings=FALSE)
checks<-character();ok<-function(x,name){stopifnot(isTRUE(x));checks<<-c(checks,name);cat('PASS:',name,'\n')};fails<-function(f,pattern){e<-tryCatch({f();''},error=conditionMessage);grepl(pattern,e)}
node<-function(id,items=character(),kind='latent',variable='',label=paste('構面',id))list(id=id,code=if(kind=='latent')paste0('F',id)else'Y',label=label,kind=kind,variable=variable,items=items)
edge<-function(from,to,type='regression')list(from=from,to=to,type=type)
vars<-c(paste0('q',1:9),'y');ns<-list(node('1',vars[1:3],label='工作環境'),node('2',vars[4:6],label='疲勞'),node('3',vars[7:9],label='職能認知'),node('4',kind='observed',variable='y',label='衛生所轉型'));es<-list(edge('1','2'),edge('2','3'),edge('3','4'),edge('1','4'))
s<-sem_build_spec(ns,es,vars);pt<-lavaan::lavaanify(s$syntax)
ok(sum(pt$op=='=~')==9&&sum(pt$op=='~')==4,'guided model has exactly selected indicators and four paths')
ok(any(pt$lhs=='y'&pt$rhs=='F3'&pt$op=='~')&&!any(pt$lhs=='F1'&pt$rhs=='F2'&pt$op=='~'),'arrow direction maps to lavaan outcome ~ predictor')
ok(fails(function()sem_build_spec(ns,c(es,list(edge('2','1'))),vars),'循環'),'feedback cycle rejected')
bad<-ns;bad[[2]]$items<-vars[1:3];ok(fails(function()sem_build_spec(bad,es,vars),'同一題'),'duplicate indicators rejected')
bad<-ns;bad[[1]]$items<-vars[1:2];ok(fails(function()sem_build_spec(bad,es,vars),'至少 3'),'underidentified two-item guided construct rejected')
ok(fails(function()sem_build_spec(ns,c(es,es[1]),vars),'重複'),'duplicate path rejected')
ok(fails(function()sem_build_spec(ns,list(edge('1','')),vars),'起點'),'unfinished path rejected')
ok(fails(function()sem_build_spec(ns,es,setdiff(vars,'q1')),'不存在'),'excluded variable rejected')
g<-list(list(label='工作環境',items=vars[1:3]),list(label='疲勞',items=vars[4:6]));eg<-efa_build_spec(g,vars)
ok(length(eg$items)==6&&grepl('工作環境 = q1, q2, q3',eg$groups,fixed=TRUE),'EFA cards serialize distinct selected groups')
badg<-g;badg[[2]]$items<-vars[2:4];ok(fails(function()efa_build_spec(badg,vars),'重複'),'EFA overlapping groups rejected')
# Independent synthetic sample with a known population model; no user data.
set.seed(711);n<-900;latent1<-rnorm(n);latent2<-.45*latent1+rnorm(n);latent3<-.5*latent2+rnorm(n);d<-data.frame(y=.5*latent3+.2*latent1+rnorm(n));for(i in 1:9)d[[paste0('q',i)]]<-.8*list(latent1,latent2,latent3)[[ceiling(i/3)]]+rnorm(n,sd=.55)
a<-sem_analysis(d,s$syntax,node_labels=s$labels)
ok('SEM_diagram'%in%names(a$plots),'SEM publication diagram generated')
ok(nrow(a$tables$SEM_diagram_edges)==13,'diagram includes all nine measurement and four structural edges')
ref<-lavaan::sem(s$syntax,data=d,estimator='MLR');rpe<-lavaan::parameterEstimates(ref,standardized=TRUE);de<-a$tables$SEM_diagram_edges;idx<-which(de$From=='F1'&de$To=='F2');ri<-which(rpe$lhs=='F2'&rpe$rhs=='F1'&rpe$op=='~')
ok(abs(de$Std[idx]-rpe$std.all[ri])<1e-10&&abs(de$p_value[idx]-rpe$pvalue[ri])<1e-10,'diagram coefficients and p values match fitted lavaan output')
fs<-a$tables$SEM_fit_summary;fm<-lavaan::fitMeasures(ref);ok(all(abs(fs$Value[!is.na(fs$Source)&fs$Index!='Chi_square_df']-fm[fs$Source[!is.na(fs$Source)&fs$Index!='Chi_square_df']])<1e-10),'robust fit summary matches recorded lavaan indices')
ggplot2::ggsave('test-output/SEM_builder_demo.png',a$plots$SEM_diagram,width=16,height=9,dpi=130,bg='white')
source('R/result_ui.R',encoding='UTF-8');write_plot(a$plots$SEM_diagram,'test-output/SEM_builder_demo.pdf','pdf');ok(file.info('test-output/SEM_builder_demo.pdf')$size>1000,'vector PDF export succeeds')
a<-analysis_provenance(a,'sem',list(estimator='MLR',design='cross',structure='independent'))
ok('lavaan'%in%a$provenance$statistics$Package&&'ggplot2'%in%a$provenance$plotting$Package&&!any(a$provenance$statistics$Package%in%a$provenance$plotting$Package),'statistical and plotting package versions separated')
export_xlsx(a,'test-output/SEM_builder_demo.xlsx');ok(all(c('Statistical_packages','Plotting_packages')%in%readxl::excel_sheets('test-output/SEM_builder_demo.xlsx')),'Excel preserves separate package sheets')
writeLines(paste('PASS',checks),'test-output/model_builder_checks.txt',useBytes=TRUE);saveRDS(a,'test-output/SEM_builder_demo.rds');cat(length(checks),'checks passed\n')
