Sys.setlocale('LC_CTYPE','English_United States.utf8');source('app.R',encoding='UTF-8')
dir.create('test-output',showWarnings=FALSE)
checks<-character();ok<-function(x,label){stopifnot(isTRUE(x));checks<<-c(checks,label);cat('PASS:',label,'\n')}
fails<-function(expr,text){e<-tryCatch({force(expr);''},error=conditionMessage);grepl(text,e,fixed=TRUE)}
# Synthetic responses only: same item allocation as the reported screenshot.
set.seed(913);n<-1200;latent_a<-rnorm(n);latent_b<-.45*latent_a+rnorm(n)
z<-data.frame(Q1=latent_a+rnorm(n,sd=.7),Q2=latent_a+rnorm(n,sd=.8),Q3=latent_b+rnorm(n,sd=.7),Q4=latent_a+rnorm(n,sd=.9),Q5=latent_b+rnorm(n,sd=.8),Q6=latent_b+rnorm(n,sd=.9))
ord<-as.data.frame(lapply(z,function(v)ordered(cut(v,c(-Inf,-.8,0,.8,Inf),labels=c('很低','低','高','很高')))))
syn<-'F1 =~ Q1 + Q2 + Q4\nF2 =~ Q3 + Q5 + Q6\nF2 ~ F1';pt<-lavaan::lavaanify(syn)
a<-sem_analysis(ord,syn,estimator='WLSMV')
ok(setequal(a$sem_type_spec$ordered,names(ord))&&length(a$sem_type_spec$requested)==0&&'SEM_diagram'%in%names(a$plots),'six ordinal items run without redundant checkbox selection')
direct<-lavaan::sem(syn,ord,ordered=names(ord),estimator='WLSMV',missing='listwise')
ok(isTRUE(all.equal(a$tables$Parameters$est,lavaan::parameterEstimates(direct)$est,tolerance=1e-10)),'automatic WLSMV estimates equal direct lavaan estimates')
ok(all(a$tables$SEM_variable_types$Level_order=='很低 < 低 < 高 < 很高'),'nonalphabetic user-defined category order preserved')
manual<-sem_analysis(ord,syn,names(ord),estimator='WLSMV')
ok(isTRUE(all.equal(a$tables$Parameters$est,manual$tables$Parameters$est,tolerance=1e-10)),'existing explicit ordinal selections remain compatible')
cf<-cfa_analysis(ord,sub('\nF2 ~ F1','',syn,fixed=TRUE),estimator='WLSMV')
ok(length(cf$sem_type_spec$ordered)==6,'CFA uses the same automatic ordinal handling')
mixed<-ord;mixed$Q4<-z$Q4;mixed$Y<-ordered(cut(.5*latent_b+rnorm(n),c(-Inf,-.6,.6,Inf),labels=c('低','中','高')))
mx<-sem_analysis(mixed,paste(syn,'Y ~ F2',sep='\n'),estimator='WLSMV')
ok(!'Q4'%in%mx$sem_type_spec$ordered&&'Y'%in%mx$sem_type_spec$ordered&&'HTMT2'%in%names(mx$tables),'mixed continuous and ordinal indicators plus ordinal outcome work')
numeric_ord<-as.data.frame(lapply(ord,as.integer))
write.csv(numeric_ord,'test-output/SEM_ordered_synthetic.csv',row.names=FALSE)
nm<-sem_analysis(numeric_ord,syn,names(numeric_ord),estimator='WLSMV')
ok(isTRUE(all.equal(a$tables$Parameters$est,nm$tables$Parameters$est,tolerance=1e-10)),'numeric ordinal override keeps ascending score order')
ok(fails(sem_variable_spec(ord,pt,estimator='MLR'),'請將估計法改為 WLSMV'),'MLR with ordered items receives an actionable estimator message')
nom<-ord;nom$Q1<-factor(nom$Q1,ordered=FALSE)
ok(fails(sem_variable_spec(nom,pt,estimator='WLSMV'),'尚未指定類別順序'),'WLSMV alone does not silently assign order to nominal items')
badx<-ord;badx$x<-ord$Q1
ok(fails(sem_variable_spec(badx,lavaan::lavaanify(paste(syn,'F2 ~ x',sep='\n')),estimator='WLSMV'),'外生預測變項'),'ordinal exogenous predictor requires explicit numeric or dummy coding')
ok(fails(sem_variable_spec(ord,pt,'outside',estimator='WLSMV'),'未納入模型'),'stale manually selected fields are reported clearly')
badlevel<-ord;badlevel$Q1<-ordered(rep('低',n),levels=levels(ord$Q1))
ok(fails(sem_analysis(badlevel,syn,estimator='WLSMV'),'少於兩個有效類別'),'constant ordinal item stops before fitting')
unused<-ord;levels(unused$Q1)<-c(levels(unused$Q1),'未出現')
un<-sem_analysis(unused,syn,estimator='WLSMV')
ok(grepl('未出現',un$tables$SEM_variable_types$Level_order[1])&&!grepl('未出現',un$tables$SEM_variable_types$Analyzed_level_order[1]),'unused levels recorded without changing analyzed category order')
shiny::testServer(server,{
 ingest(ord,'Synthetic ordinal regression test');session$flushReact()
 session$setInputs(design='cross',structure='independent',purpose='path',module='sem',sem_entry='builder',estimator='WLSMV',ordered=character(),B=20,bootstrap_ci=FALSE,seed=913,validation='same')
 session$setInputs(sem_node_1_code='F1',sem_node_1_kind='latent',sem_node_1_items=c('Q1','Q2','Q4'))
 session$setInputs(sem_y_kind='latent',sem_y_items=c('Q3','Q5','Q6'),builder_action=list(action='add_edge',id=''))
 session$setInputs(sem_edge_1_from='1',sem_edge_1_to='outcome',sem_edge_1_type='regression',run=1)
 ok(result()$title!='分析未完成'&&length(result()$settings$ordered)==6&&length(result()$settings$ordered_requested)==0,'full SEM builder runs and freezes actual ordinal fields')
 ok(grepl('自動套用',as.character(output$sem_type_preview$html))&&grepl('可以送出估計',as.character(output$sem_builder_preview$html)),'preview confirms actual types and estimator')
 frozen<-result();session$setInputs(estimator='MLR')
 ok(grepl('WLSMV',as.character(output$sem_builder_preview$html))&&!grepl('可以送出估計',as.character(output$sem_builder_preview$html)),'preview no longer claims ready under incompatible estimator')
 ok(identical(result()$settings$estimator,'WLSMV')&&any(grepl('DWLS',result()$provenance$logic)),'completed result provenance remains frozen after control edits')
 # Capture actual Shiny notification messages across repeated failed runs.
 notifications<-list();session$sendNotification<-function(type,message){notifications[[length(notifications)+1L]]<<-list(type=type,message=message)}
 session$setInputs(run=2);session$setInputs(run=3)
 added<-Filter(function(x)x$type=='show',notifications)
 ok(length(added)==2&&all(vapply(added,function(x)identical(x$message$id,'analysis-error')&&identical(x$message$duration,12000),logical(1))),'repeated failures replace the same finite-duration notification')
 session$setInputs(estimator='WLSMV',run=4)
 ok(result()$title!='分析未完成'&&any(vapply(notifications,function(x)x$type=='remove'&&identical(x$message,'analysis-error'),logical(1))),'corrected rerun clears old error and produces result')
 session$setInputs(purpose='measurement',module='cfa',cfa_entry='syntax',cfa_syntax=sub('\nF2 ~ F1','',syn,fixed=TRUE),run=5)
 ok(result()$title=='驗證性因素分析 CFA'&&length(result()$settings$ordered)==6,'CFA interface runs ordinal data without additional selections')
 saveRDS(frozen,'test-output/SEM_ordered_result.rds')
})
writeLines(checks,'test-output/sem_ordered_checks.txt',useBytes=TRUE)
