# Run from project root: Rscript tests/test_engine.R
if(.Platform$OS.type=='windows')Sys.setlocale('LC_CTYPE','English_United States.utf8')
lib<-Sys.getenv('BIOSTAT_LIBRARY','library');if(dir.exists(lib)).libPaths(c(normalizePath(lib),.libPaths()))
source('R/core.R',encoding='UTF-8');source('R/models.R',encoding='UTF-8');source('R/export.R',encoding='UTF-8');source('R/diagnostics.R',encoding='UTF-8')
dir.create('test-output',showWarnings=FALSE)
fail<-character();passed<-character()
test<-function(name,expr){cat('TEST',name,'... ');tryCatch({force(expr);passed<<-c(passed,name);cat('PASS\n')},error=function(e){fail<<-c(fail,paste(name,conditionMessage(e)));cat('FAIL:',conditionMessage(e),'\n')})}
must_fail<-function(expr){e<-tryCatch({force(expr);NULL},error=identity);stopifnot(inherits(e,'error'))}
set.seed(134);n<-500;d<-data.frame(A=factor(rbinom(n,1,.5)),Z=factor(rbinom(n,1,.5)),Age=runif(n,25,75));d$Y<-rbinom(n,1,plogis(-2+.3*num(d$A)+.4*num(d$Z)+.3*num(d$A)*num(d$Z)));d$C<-1+.2*num(d$A)+.03*d$Age+rnorm(n);d$Count<-rnbinom(n,mu=2,size=2);d$Time<-rexp(n,.03);d$Event<-factor(rbinom(n,1,.6));d$ID<-1:n;d$Inst<-rnorm(n);d$Endo<-.8*d$Inst+rnorm(n);d$IVY<-1.5*d$Endo+rnorm(n)
test('p values and rounding',{stopifnot(identical(fp(c(.123456,.00009,4e-8,5e-8)),c('0.1235','<0.0001','<5×10⁻⁸','<0.0001')));stopifnot(display_table(data.frame(Index='pvalue',Value=.000012))$Value=='<0.0001')})
test('Table1 real counts',{a<-descriptive(d,c('A','Age'),'Z');stopifnot(any(grepl('n [(]%[)]',a$tables$Table1$Characteristic)),any(grepl('[(][0-9]+[.][0-9]{2}[)]',a$tables$Table1$Overall)));export_xlsx(a,'test-output/table1.xlsx')})
test('Welch matches R',{a<-comparison(d,'C','A','welch');stopifnot(all.equal(a$tables$Test$p_value,t.test(C~A,d)$p.value))})
test('Fisher comparison',{comparison(d,'Y','A','fisher')})
test('Spearman and Holm',{a<-correlation(d,c('C','Age','Count'),'spearman');stopifnot(nrow(a$tables$Pairs)==3)})
test('Linear HC3',{a<-regression(d,'C',c('A','Age'),'linear');f<-lm(C~A+Age,d);stopifnot(max(abs(a$tables$Coefficients$Beta-coef(f)))<1e-10)})
test('Logistic interaction and standardized risks',{a<-regression(d,'Y',c('A','Z','Age'),'logistic','cohort','1',c('A','Z'));stopifnot('Additive_interaction'%in%names(a$tables));saveRDS(a,'test-output/logistic.rds');for(nm in names(a$plots))ggplot2::ggsave(paste0('test-output/',nm,'.png'),a$plots[[nm]],width=8,height=4,dpi=100)})
test('RR HC0 and no LRT',{a<-regression(d,'Y',c('A','Z'),'rr','cohort','1',c('A','Z'));stopifnot('RR'%in%names(a$tables$Coefficients),!'Interaction_LRT'%in%names(a$tables))})
test('Case-control refuses RR',{must_fail(regression(d,'Y','A','rr','casecontrol','1'))})
test('Poisson and negative binomial',{regression(d,'Count',c('Age','A'),'poisson');regression(d,'Count','Age','negbin')})
test('Ordinal model',{dd<-d;dd$Ord<-ordered(cut(d$C,quantile(d$C,c(0,.33,.66,1)),include.lowest=TRUE));regression(dd,'Ord',c('A','Age'),'ordinal')})
test('Multinomial model',{dd<-d;dd$Nom<-factor(sample(letters[1:3],nrow(d),TRUE));regression(dd,'Nom',c('A','Age'),'multinomial')})
test('2x2 known risk ratio and risk difference',{dd<-data.frame(Y=c(rep(1,20),rep(0,80),rep(1,10),rep(0,90)),A=factor(rep(c('1','0'),each=100)));a<-effects2x2(dd,'Y','A','1','1','cohort');stopifnot(abs(a$tables$Effects$Estimate[2]-2)<1e-12,abs(a$tables$Effects$Estimate[3]-.1)<1e-12);b<-effects2x2(dd,'Y','A','1','1','casecontrol');stopifnot(nrow(b$tables$Effects)==1)})
test('Zero cells preserve absence of log RR CI',{dd<-data.frame(Y=c(rep(0,20),rep(1,10),rep(0,10)),A=factor(rep(c('1','0'),each=20)));a<-effects2x2(dd,'Y','A','1','1','cohort');stopifnot(is.na(a$tables$Effects$CI_low[2]))})
test('Cox KM PH and interaction',{a<-survival_analysis(d,'Time','Event','1',c('A','Z','Age'),'A','ID',inter=c('A','Z'));stopifnot('PH_test'%in%names(a$tables))})
test('AG and overlap validation',{dd<-d;dd$Start<-0;a<-survival_analysis(dd,'Time','Event','1',c('A','Age'),id='ID',start='Start',ag=TRUE);dd<-rbind(dd,dd[1,]);must_fail(survival_analysis(dd,'Time','Event','1','Age',id='ID',start='Start',ag=TRUE))})
test('2SLS recovers simulated effect',{a<-iv_analysis(d,'IVY','Endo','Inst');stopifnot(abs(a$tables$Coefficients$Beta[2]-1.5)<.2)})
test('ROC direction',{a<-roc_analysis(d,'Y','C','1');stopifnot(a$tables$AUC$AUC>=0,a$tables$AUC$AUC<=1)})
set.seed(201);nn<-220;latent<-rnorm(nn);q<-as.data.frame(sapply(1:4,function(j)as.integer(cut(latent+rnorm(nn),c(-Inf,-.7,0,.7,Inf)))));names(q)<-paste0('Q',1:4)
test('Alpha matches psych',{stopifnot(abs(raw_alpha(q)-psych::alpha(q,check.keys=FALSE)$total$raw_alpha)<1e-10)})
test('Reverse bounds required',{must_fail(questionnaire(q,c('Q1','Q2'),'Q2',boot=FALSE,efa=FALSE))})
test('Two items no EFA',{a<-questionnaire(q,c('Q1','Q2'),boot=FALSE);stopifnot('Two_item'%in%names(a$tables),!'Loadings'%in%names(a$tables))})
test('Constant item rejected',{qq<-q;qq$Q1<-1;must_fail(questionnaire(qq,names(qq),boot=FALSE))})
test('Non PD SMC rejects',{must_fail(smc_eigen(matrix(c(1,1,1,1),2,2)))})
test('Parallel reproducibility and PAF',{a<-questionnaire(q,names(q),B=20,boot=FALSE,seed=311);b<-parallel_analysis(q,20,311);stopifnot(identical(a$tables$Parallel,b$table),a$tables$PA_status$Successful==20);saveRDS(a,'test-output/efa.rds')})
test('Bootstrap 5000 alpha',{a<-boot_cases(q,function(z)c(Alpha=raw_alpha(z)),5000,1);stopifnot(a$table$Successful==5000,a$table$CI_low<a$table$Estimate,a$table$CI_high>a$table$Estimate)})
test('Bootstrap failures are reported',{a<-boot_cases(data.frame(x=c(0,0,1)),function(z)c(Value=if(length(unique(z$x))>1)mean(z$x)else NA_real_),50,1);stopifnot(a$table$Successful<50,is.na(a$table$CI_low))})
test('Estimator RNG cannot duplicate resamples',{a<-boot_cases(data.frame(x=1:100),function(z){set.seed(1);c(Mean=mean(z$x))},30,12);stopifnot(sd(a$samples[,1])>0,a$table$CI_low<a$table$CI_high)})
set.seed(800);f1<-rnorm(450);factor2<-.5*f1+rnorm(450);s<-as.data.frame(cbind(sapply(1:3,function(j)f1+rnorm(450,.0,.6)),sapply(1:3,function(j)factor2+rnorm(450,0,.6))));names(s)<-paste0('Q',1:6);syn<-'F1 =~ Q1+Q2+Q3\nF2 =~ Q4+Q5+Q6\nF2 ~ F1'
test('SEM MLR AVE HTMT',{a<-sem_analysis(s,syn);stopifnot('HTMT2'%in%names(a$tables),'AVE'%in%names(a$tables));saveRDS(a,'test-output/sem.rds')})
test('SEM WLSMV',{ss<-as.data.frame(lapply(s,function(a)ordered(cut(a,c(-Inf,-1,0,1,Inf)))));a<-sem_analysis(ss,syn,names(ss),'WLSMV');stopifnot('Parameters'%in%names(a$tables))})
test('SEM bootstrap refits',{a<-sem_analysis(s,syn,B=20,boot=TRUE);stopifnot(all(a$tables$Bootstrap_parameters$Requested==20))})
test('Real Word and Excel exports',{a<-readRDS('test-output/logistic.rds');export_docx(a,'test-output/report.docx');export_xlsx(a,'test-output/report.xlsx');stopifnot('word/document.xml'%in%unzip('test-output/report.docx',list=TRUE)$Name,'xl/workbook.xml'%in%unzip('test-output/report.xlsx',list=TRUE)$Name)})
writeLines(c(paste('PASS',length(passed)),paste('FAIL',length(fail)),passed,fail,capture.output(sessionInfo())),'test-output/test-summary.txt')
if(length(fail))stop(paste(fail,collapse='\n'))
